apiVersion: apps/v1
kind: Deployment
metadata:
  name: angulartourofheroes-deployment

spec:
  selector:
    matchLabels:
      app: sample-angular-app
  replicas: 2
  template:
    metadata:
      labels:
        app: sample-angular-app
    spec:
      containers:
      - name: angulartouroferoes
        image: amit4498/demoapps
        ports:
        - containerPort: 8080