name: Build using actions

on:
  workflow_dispatch:
  
jobs: 
  angular-tour-of-heros:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout to repo
        uses: actions/checkout@v3
      - run: |
          pwd 

      - name: build using action.yaml
        uses: ./.github/actions
        with:
          app-dir: "./"

