# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  push:
    branches:
      - develop

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: amit4498
          password: Amit@1234

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: amit4498/demoapps
          
      #- name: Build and push Docker image
       # uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        #with:
         # context: .
          #push: true
          #tags: ${{ steps.meta.outputs.tags }}
          #labels: ${{ steps.meta.outputs.labels }}

      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: check te path PWD
        run: |
          pwd

      - name: Build and push Docker images
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        uses: docker/build-push-action@v4.0.0
        with:
          # Build's context is the set of files located in the specified PATH or URL
          #context: # optional
          # Path to the Dockerfile
          file: Dockerfile
          # List of metadata for an image
          labels: 1
          # Always attempt to pull all referenced images
          #pull: true
          # Push is a shorthand for --output=type=registry
          push: true
          # List of tags
          tags: angularheroapp
